---
  - name: Install Docker Module for Python
    pip:
      name: docker

  - name: Pull App Docker image
    docker_image:
      name: "{{ app_image_name }}:{{ app_image_tag }}"
      source: pull

  - name: Stop and remove existing App container
    docker_container:
      name: "{{ app_container_name }}"
      state: absent

  - name: Run App Docker container
    docker_container:
      name: "{{ app_container_name }}"
      image: "{{ app_image_name }}:{{ app_image_tag }}"
      ports: "8090:80"
      state: started
